name: ✨

on: [pull_request]

jobs:
  style-checks-rust:
    name: 🦀 style (${{ matrix.feature-flags }})
    runs-on: codeberg-medium
    strategy:
      matrix:
        feature-flags:
          - '--no-default-features --features "strict,openblas-system"'
          - '--features "strict,openblas-system"'
          - '--all-features'
    steps:
      - name: Set up Rust
        uses: https://github.com/dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt,clippy
      - name: Set up MPI
        uses: https://github.com/mpi4py/setup-mpi@v1
        with:
          mpi: mpich
      - uses: actions/checkout@v6
      - name: apt-get update
        run: sudo apt-get update
      - name: Install clang cmake
        run: sudo apt-get install -y libclang-dev cmake
      - name: Install LAPACK, OpenBLAS, SCOTCH
        run: sudo apt-get install -y libopenblas-dev liblapack-dev libscotch-dev

      - name: Rust style checks
        run: |
          cargo fmt -- --check
          cargo clippy ${{ matrix.feature-flags }} -- -D warnings
          cargo clippy --tests ${{ matrix.feature-flags }} -- -D warnings
          cargo clippy --examples ${{ matrix.feature-flags }} -- -D warnings

  style-checks-python:
    name: 🐍 style
    runs-on: codeberg-small
    steps:
      - name: Set up Python
        uses: https://github.com/actions/setup-python@v5
        with:
          python-version: "3.14"
      - uses: actions/checkout@v6
      - run: |
          python3 -m pip install ruff mypy
        name: Install Ruff and mypy
      - run: |
          cd ndelement
          python3 -m ruff check python
          python3 -m ruff format --check python
        name: Run ruff checks
      - run: |
          cd ndelement
          python3 -m mypy python
        name: Run mypy checks
