name: 🧪

on: [push, pull_request]

jobs:
  run-tests-python:
    name: 🐍 tests (${{ matrix.python-version}})
    runs-on: codeberg-medium
    strategy:
      matrix:
        python-version: ["3.14"]
         python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v6
      - name: apt-get update
        run: sudo apt-get update
      - name: Install clang cmake
        run: sudo apt-get install -y libclang-dev cmake
      - name: Install LAPACK, OpenBLAS, SCOTCH
        run: sudo apt-get install -y libopenblas-dev liblapack-dev libscotch-dev
      - name: Install uv
        run: pip install uv "maturin>=1.7"

      - name: Make virtual environment for ndelement
        run: |
          cd ndelement
          uv venv .venv
      - name: Install ndelement Python package
        run: |
          cd ndelement
          source .venv/bin/activate
          maturin develop --features "ci"
      - name: Run ndelement Python tests
        run: |
          cd ndelement
          source .venv/bin/activate
          python -m pytest python/test
